version: "3.9"

name: fin_tracker 

volumes:
  mongodb_data:

networks:
  ft-net:
    driver: bridge

x-common: &common
  env_file:  /home/sanjay/Application/FinTrack/.env


services:

 version: "3.8"

services:
  mongodb:
    image: mongo:7
    hostname: mongodb
    restart: unless-stopped
    #command: ["mongod", "--config", "/etc/mongod.conf"]
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
    volumes:
      - mongodb_data:/data/db
      - ../db/config/mongod.conf:/etc/mongod.conf:ro
      - ../db/certs:/certs:ro
    networks:
      - ft-net

  mongo-express:
    image: mongo-express:latest
    hostname: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      # ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      # ME_CONFIG_MONGODB_SERVER: mongodb
      # ME_CONFIG_MONGODB_SSL: "true"
      # ME_CONFIG_MONGODB_SSL_CA_FILE: /certs/ca.pem
      # ME_CONFIG_MONGODB_SSL_CERT_FILE: /certs/client-cert.pem
    volumes:
      - ../db/certs:/certs:ro
    depends_on:
      - mongodb
    networks:
      - ft-net
  


  # backend:
    # build:
    #   context: ../backend
    #   dockerfile: Dockerfile
    # container_name: ft_backend
    # restart: unless-stopped
    # ports:
    #   - "8000:8000"
    # volumes:
    #   - ../backend:/app
    # environment:
    #   DATABASE_URL: postgres://sanjay:sanjay123@db:5432/fintracker
    #   ENV: development
    # depends_on:
    #   - db
    # networks:
    #   - ft-net
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
