#!/usr/bin/env bash
# Renders the TEST server's .env -- same key set as scripts/deploy/render_env.sh
# (production), but each key prefers a TEST_<KEY> secret/variable over the plain
# <KEY> one, falling back to <KEY> when no TEST_ override is configured.
# See docs/CICD.md "Test pipeline" for the exact GitHub Secret/Variable names.
#
# Runs on the GitHub Actions runner (not the server); the caller redirects stdout
# to a file that .github/actions/test-deploy writes to the test server. Which
# source each key resolved from (never the value) is logged to stderr so the run
# log clearly shows what's overridden vs falling back to production config.
#
# FINTRACKER_VERSION is a deployment mechanic, not an app secret/variable pair:
# the caller exports it directly (as "<version>-test") before running this script.
set -Eeuo pipefail

kv() {
  local key="$1" test_key="TEST_$1" value src
  if [ -n "${!test_key:-}" ]; then
    value="${!test_key}"; src="TEST_${key}"
  else
    value="${!key:-}"; src="production fallback"
  fi
  printf '  %-40s -> %s\n' "$key" "$src" >&2
  printf '%s=%s\n' "$key" "$value"
}

# Same "at least these" list as render_env.sh, checked against TEST_<KEY> OR <KEY>.
REQUIRED_KEYS=(FT_SESSION_SECRET FT_BASE_URL FT_DEFAULT_ADMIN_PASSWORD ME_CONFIG_BASICAUTH_PASSWORD)
missing=()
for key in "${REQUIRED_KEYS[@]}"; do
  test_key="TEST_$key"
  if [ -z "${!test_key:-}" ] && [ -z "${!key:-}" ]; then
    missing+=("$key")
  fi
done
if [ "${#missing[@]}" -gt 0 ]; then
  printf 'render_test_env.sh: required value(s) missing -- set TEST_<KEY> or <KEY> as GitHub Secrets/Variables: %s\n' \
    "${missing[*]}" >&2
  exit 1
fi

echo "Environment variable resolution:" >&2

cat <<'EOF'
# Generated by scripts/deploy/render_test_env.sh -- do not edit by hand.
# TEST_<KEY> overrides <KEY> where configured; otherwise falls back to production.
EOF

echo
printf 'FINTRACKER_VERSION=%s\n' "${FINTRACKER_VERSION:?FINTRACKER_VERSION must be exported by the caller}"

echo
echo "# --- Core App ---"
kv FT_ENV
kv FT_APP_NAME
kv FT_APP_VERSION
kv FT_BASE_URL
kv FT_SESSION_SECRET
kv FT_EXTERNAL_PASSWORD_RESET_URL

echo
echo "# --- Authentication / Google OAuth ---"
kv FT_GOOGLE_CLIENT_ID
kv FT_GOOGLE_CLIENT_SECRET
kv FT_GOOGLE_ADMIN_EMAILS
kv FT_AUTH_ENABLED
kv FT_AUTH_PROVIDER
kv FT_AUTH_ALLOW_LOCAL_LOGIN

echo
echo "# --- Bootstrap Admin ---"
kv FT_DEFAULT_ADMIN_USERNAME
kv FT_DEFAULT_ADMIN_PASSWORD
kv FT_DEFAULT_ADMIN_EMAIL

echo
echo "# --- Database ---"
kv FT_MONGO_URI
kv FT_MONGO_DB_NAME
kv FT_CERTS_DIR
kv FT_MONGO_TRANSACTIONS
kv FT_DB_ENABLED

echo
echo "# --- Admin Application Defaults ---"
kv FT_APP_LOGO_URL
kv FT_SUPPORT_EMAIL
kv FT_SUPPORT_PHONE
kv FT_MAINTENANCE_MODE
kv FT_MAINTENANCE_MESSAGE

echo
echo "# --- SMTP ---"
kv FT_SMTP_ENABLED
kv FT_SMTP_HOST
kv FT_SMTP_PORT
kv FT_SMTP_USERNAME
kv FT_SMTP_PASSWORD
kv FT_SMTP_FROM
kv FT_SMTP_TLS

echo
echo "# --- Telegram ---"
kv FT_TELEGRAM_ENABLED
kv FT_TELEGRAM_BOT_USERNAME
kv FT_TELEGRAM_BOT_TOKEN
kv FT_TELEGRAM_WEBHOOK_URL
kv FT_TELEGRAM_WEBHOOK_SECRET
kv FT_TELEGRAM_POLLING_ENABLED

echo
echo "# --- Push Notifications ---"
kv FT_PUSH_ENABLED
kv FT_PUSH_VAPID_PUBLIC_KEY
kv FT_PUSH_FIREBASE_API_KEY
kv FT_PUSH_FIREBASE_AUTH_DOMAIN
kv FT_PUSH_FIREBASE_PROJECT_ID
kv FT_PUSH_FIREBASE_STORAGE_BUCKET
kv FT_PUSH_FIREBASE_MESSAGING_SENDER_ID
kv FT_PUSH_FIREBASE_APP_ID
kv FT_PUSH_FIREBASE_MEASUREMENT_ID
kv FT_PUSH_FIREBASE_SERVICE_ACCOUNT_JSON

echo
echo "# --- Backup Defaults ---"
kv FT_BACKUP_ENABLED
kv FT_BACKUP_PROVIDER
kv FT_BACKUP_SCHEDULE_TIME
kv FT_BACKUP_RETENTION_DAYS
kv FT_BACKUP_DESTINATION

echo
echo "# --- Logging and Scheduler ---"
kv FT_LOG_LEVEL
kv FT_DEBUG_LOG
kv PORT
kv FT_APP_PORT
kv FT_SCHEDULER_ENABLED
kv FT_SETTINGS_CACHE_SECONDS
kv FT_LOG_DIR
kv FT_LOG_FILE
kv FT_AUDIT_LOG_FILE
kv FT_TELEGRAM_LOG_FILE
kv FT_SCHEDULER_LOG_FILE
kv FT_ERROR_LOG_FILE
kv FT_LOG_MAX_BYTES
kv FT_LOG_BACKUP_COUNT
kv SCHEDULER_RUN_TIME
kv FT_NOTIFICATION_ALERT_INTERVAL_SECONDS

echo
echo "# --- AI ---"
kv OPENAI_API_KEY

echo
echo "# --- Docker Compose (test stack) ---"
kv FT_PUBLIC_PORT
kv FT_MONGO_BIND
kv FT_MONGO_PORT
kv FT_MONGO_EXPRESS_BIND
kv FT_MONGO_EXPRESS_PORT
kv FT_MONGO_IMAGE_TAG
kv FT_MONGO_VOLUME
kv MONGO_INITDB_DATABASE
kv MONGO_INITDB_ROOT_USERNAME
kv MONGO_INITDB_ROOT_PASSWORD
kv ME_CONFIG_MONGODB_SERVER
kv ME_CONFIG_MONGODB_PORT
kv ME_CONFIG_BASICAUTH_USERNAME
kv ME_CONFIG_BASICAUTH_PASSWORD
kv ME_CONFIG_OPTIONS_EDITORTHEME
