#!/usr/bin/env bash
# Renders the server's .env from process environment variables set by
# .github/workflows/publish-main.yml (one GitHub Secret or Variable per key,
# named identically to the key below -- see docs/CICD.md for the full list).
#
# Runs on the GitHub Actions runner, not on the server. Prints to stdout;
# the caller redirects it to a file that is later streamed to the server by
# .github/actions/sync-server. A key with no matching secret/variable is
# rendered empty, which is equivalent to leaving it unset in env.example
# (compose's ${VAR:-default} substitution treats empty the same as unset).
set -Eeuo pipefail

kv() { printf '%s=%s\n' "$1" "${!1:-}"; }

# Keys with no compose-level default or requirement (deploy/README.md's "at least these"
# list). Empty here means the app silently runs with a blank secret/URL, so fail the
# GitHub Actions job loudly instead, before anything is sent to the server.
REQUIRED_KEYS=(FT_SESSION_SECRET FT_BASE_URL FT_DEFAULT_ADMIN_PASSWORD ME_CONFIG_BASICAUTH_PASSWORD)
missing=()
for key in "${REQUIRED_KEYS[@]}"; do
  [ -n "${!key:-}" ] || missing+=("$key")
done
if [ "${#missing[@]}" -gt 0 ]; then
  printf 'render_env.sh: required value(s) missing -- set these as GitHub Secrets/Variables: %s\n' \
    "${missing[*]}" >&2
  exit 1
fi

cat <<'EOF'
# Generated by scripts/deploy/render_env.sh -- do not edit by hand.
# Source of truth is GitHub Secrets/Variables; re-run the workflow to refresh.
EOF

echo
echo "# --- Core App ---"
kv FT_ENV
kv FT_APP_NAME
kv FT_APP_VERSION
kv FT_BASE_URL
kv FT_SESSION_SECRET
kv FT_EXTERNAL_PASSWORD_RESET_URL

echo
echo "# --- Authentication / Google OAuth ---"
kv FT_GOOGLE_CLIENT_ID
kv FT_GOOGLE_CLIENT_SECRET
kv FT_GOOGLE_ADMIN_EMAILS
kv FT_AUTH_ENABLED
kv FT_AUTH_PROVIDER
kv FT_AUTH_ALLOW_LOCAL_LOGIN

echo
echo "# --- Bootstrap Admin ---"
kv FT_DEFAULT_ADMIN_USERNAME
kv FT_DEFAULT_ADMIN_PASSWORD
kv FT_DEFAULT_ADMIN_EMAIL

echo
echo "# --- Database ---"
kv FT_MONGO_URI
kv FT_MONGO_DB_NAME
kv FT_CERTS_DIR
kv FT_MONGO_TRANSACTIONS
kv FT_DB_ENABLED

echo
echo "# --- Admin Application Defaults ---"
kv FT_APP_LOGO_URL
kv FT_SUPPORT_EMAIL
kv FT_SUPPORT_PHONE
kv FT_MAINTENANCE_MODE
kv FT_MAINTENANCE_MESSAGE

echo
echo "# --- SMTP ---"
kv FT_SMTP_ENABLED
kv FT_SMTP_HOST
kv FT_SMTP_PORT
kv FT_SMTP_USERNAME
kv FT_SMTP_PASSWORD
kv FT_SMTP_FROM
kv FT_SMTP_TLS

echo
echo "# --- Telegram ---"
kv FT_TELEGRAM_ENABLED
kv FT_TELEGRAM_BOT_USERNAME
kv FT_TELEGRAM_BOT_TOKEN
kv FT_TELEGRAM_WEBHOOK_URL
kv FT_TELEGRAM_WEBHOOK_SECRET
kv FT_TELEGRAM_POLLING_ENABLED

echo
echo "# --- Push Notifications ---"
kv FT_PUSH_ENABLED
kv FT_PUSH_VAPID_PUBLIC_KEY
kv FT_PUSH_FIREBASE_API_KEY
kv FT_PUSH_FIREBASE_AUTH_DOMAIN
kv FT_PUSH_FIREBASE_PROJECT_ID
kv FT_PUSH_FIREBASE_STORAGE_BUCKET
kv FT_PUSH_FIREBASE_MESSAGING_SENDER_ID
kv FT_PUSH_FIREBASE_APP_ID
kv FT_PUSH_FIREBASE_MEASUREMENT_ID
kv FT_PUSH_FIREBASE_SERVICE_ACCOUNT_JSON

echo
echo "# --- Backup Defaults ---"
kv FT_BACKUP_ENABLED
kv FT_BACKUP_PROVIDER
kv FT_BACKUP_SCHEDULE_TIME
kv FT_BACKUP_RETENTION_DAYS
kv FT_BACKUP_DESTINATION

echo
echo "# --- Logging and Scheduler ---"
kv FT_LOG_LEVEL
kv FT_DEBUG_LOG
kv PORT
kv FT_APP_PORT
kv FT_SCHEDULER_ENABLED
kv FT_SETTINGS_CACHE_SECONDS
kv FT_LOG_DIR
kv FT_LOG_FILE
kv FT_AUDIT_LOG_FILE
kv FT_TELEGRAM_LOG_FILE
kv FT_SCHEDULER_LOG_FILE
kv FT_ERROR_LOG_FILE
kv FT_LOG_MAX_BYTES
kv FT_LOG_BACKUP_COUNT
kv SCHEDULER_RUN_TIME
kv FT_NOTIFICATION_ALERT_INTERVAL_SECONDS

echo
echo "# --- AI ---"
kv OPENAI_API_KEY

echo
echo "# --- Docker Compose (production stack: docker-compose.yml on the main branch) ---"
kv FINTRACKER_VERSION
kv FT_PUBLIC_PORT
kv FT_PUBLIC_BIND
kv FT_MONGO_BIND
kv FT_MONGO_PORT
kv FT_MONGO_EXPRESS_BIND
kv FT_MONGO_EXPRESS_PORT
kv FT_MONGO_IMAGE_TAG
kv FT_MONGO_VOLUME
kv MONGO_INITDB_DATABASE
kv MONGO_INITDB_ROOT_USERNAME
kv MONGO_INITDB_ROOT_PASSWORD
kv ME_CONFIG_MONGODB_SERVER
kv ME_CONFIG_MONGODB_PORT
kv ME_CONFIG_BASICAUTH_USERNAME
kv ME_CONFIG_BASICAUTH_PASSWORD
kv ME_CONFIG_OPTIONS_EDITORTHEME

echo
echo "# --- Reverse proxy (optional: docker-compose.nginx.yml overlay) ---"
kv FT_NGINX_ENABLED
kv FT_DOMAIN
kv FT_FINTRACKER_SUBDOMAIN
kv FT_MONGO_EXPRESS_SUBDOMAIN
kv FT_NGINX_CERTS_DIR
kv FT_NGINX_HTTP_PORT
kv FT_NGINX_HTTPS_PORT
